openapi: 3.0.0
info:
  title: Hostel Management System Documentation
  description:  
  version: 2.0
  contact:
    name: Deepak
    email: 52212203@nitkkr.ac.in

servers:
  - url: 'http://localhost:3000/'
    description: This is local server

schemes: [http, https]

tags:
  - name: Common Routes
    description: APIs for authentication
  - name: HA
    description: Hostel authorities routes
  - name: SA
    tag: 
     - HA
    description: Super Admin routes
  - name: Student
    description: Student routes
  - name: Others
    description: Others routes

components:
  securitySchemes:
    JwtCookieAuth:
      type: apiKey
      in: cookie
      name: jwt
      description: HTTP-only cookie containing the JWT token.

security:
  - JwtCookieAuth: []

paths:

#*****************************************************************************************
#*                                      Common Routes Start here
#*****************************************************************************************
  /HA/adminLogin:
    post:
      description: To Login Admin account
      tags: 
        - Common Routes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '404':
          description: User does not exist
        '400':
          description: Error Occurred in token generation
        '401':
          description: Invalid credentials
        '500':
          description: Internal Server Error
        



  /HA/adminLogout:
    get:
      description: This endpoint logs out the admin account.
      tags: 
        - Common Routes
      responses:
        '200':
          description: Logged out successfully
        '400':
          description: cookie expired
        '500':
          description: Internal Server Error




#*****************************************************************************************
#*                                      HA Routes Start here
#*****************************************************************************************


  /HA/bulkCreate:
    post:
      description: used to upload students data in bulk using csv file
      tags:
        - HA
      consumes:
      - multipart/form-data
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The CSV file to upload
      responses:
        '200':
          description: data uploaded successfully
        '400':
          description: Syntax Error
        '500':
          description: Internal Server Error


  /HA/updateBulk:
    post:
      description: Used to update students data in bulk. It will be called after bulk create API is called if there is data to be updated.
      tags:
        - HA
      consumes:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
      responses:
        '200':
          description: Data updated successfully
        '400':
          description: Bad request
        '500':
          description: Internal Server Error

  /HA/studentsInfo:
    post:
      description: Used to get student Information with filters.
      tags:
        - HA
      parameters:
        - in: query
          name: rollNo
          type: interger
        - in: query
          name: firstName
          type: interger
        - in: query
          name: lastName
          type: interger
        - in: query
          name: courseId
          type: interger
        - in: query
          name: year
          type: interger
        - in: query
          name: state
          type: interger
        - in: query
          name: page
          type: interger
        - in: query
          name: limit
          type: interger
        - in: query
          name: total
          type: interger
      responses:
        '200':
          description: json data
        '400':
          description: Bad request
        '500':
          description: Internal Server Error



#*****************************************************************************************
#*                                      SA Routes Start here
#*****************************************************************************************

#?   Manage Course Routes
  /SA/getCourses:
    get:
      description: to get available courses .
      tags: 
        - SA
      responses:
        '200':
          description: fetched successfully
        '500':
          description: Internal Server Error

  /SA/addCourse:
    post:
      description: "
        Used to add Course in Course table. \n
        Do not send empty JSON on the backend"
      tags:
        - SA
      consumes:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
             courseName: "BSC"
             department: "IIHS"
             specialization: "CS"
             courseDuration: 3

      responses:
        '200':
          description: Cousrse added successfully
          content:
           application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  courseId:
                    type: integer
                  courseName:
                    type: string
                  department:
                    type: string
                  specialization:
                    type: string
                  courseDuration:
                    type: integer
                  lastUpdatedBy:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                  last_updated_at:
                    type: string
                    format: date-time
                  deletedAt:
                    type: string
                    nullable: true
                  active:
                    type: boolean
            example:
              - courseId: 1
                courseName: "MCA"
                department: "MCA"
                specialization: null
                courseDuration: 3
                lastUpdatedBy: "admin@gmail.com"
                createdAt: "2024-03-10T17:18:34.000Z"
                last_updated_at: "2024-03-10T17:18:34.000Z"
                deletedAt: null
                active: true
              - courseId: 2
                courseName: "MBA"
                department: "MBA"
                specialization: null
                courseDuration: 3
                lastUpdatedBy: "admin@gmail.com"
                createdAt: "2024-03-10T17:18:34.000Z"
                last_updated_at: "2024-03-10T17:18:34.000Z"
                deletedAt: null
                active: true
        '400':
          description: Course Allready exists
        '500':
          description: Internal Server Error

  /SA/removeCourse:
     delete:
       description: "
        this route is used to disable or permanently delete the course \n
        Send softdelte param true if want to disable \n
        Send softdelte param false if want to delete permanently"
       tags:
         - SA
       parameters:
         - name: courseId
           in: query
           description: id of Course to Delete
           required: true
           schema:
           type: integer
         - name: softdelete
           in: query
           description: true means delete permanently, false means softdelete 
           required: true
           schema:
           type: boolean
       responses:
         '200':
           description: Cousrse added successfully
           content:
            application/json:
             schema:
               type: object
             example:
               message: "successfully deleted"
         '400':
           description: Course Not Found
           content:
            application/json:
             schema:
               type: object
             example:
               message: "course not found"
         '500':
            description: Internal Server Error

  /SA/enableCourse:
     post:
       description: "
        this route is used to enable a course if disabled \n
        Works on Course table \n
        auth required"
       tags:
         - SA
       consumes:
         - application/json
       requestBody:
         required: true
         content:
           application/json:
            schema:
              type: object
            example:
             courseId: 1
       responses:
         '200':
           description: Course successfully enabled
           content:
            application/json:
             schema:
               type: object
             example:
               message: "successfully enabled"
         '400':
           description: Course Not Found or Already email enabled
           content:
            application/json:
             schema:
               type: object
             example:
               message: "Course Not Found or Already email enabled"
         '500':
            description: Internal Server Error
          

  /SA/updateCourse:
     patch:
       description: "
        this route is used to update  a course \n
        Works on Course table \n
        auth required"
       tags:
         - SA
       consumes:
         - application/json
       requestBody:
         required: true
         content:
           application/json:
            schema:
              type: object
            example:
             courseId: 1
             courseName: "BTech"
             department: "BTech"
             specialization: "CS"
             courseDuration: 4
       responses:
         '200':
           description: Course Updated successfully
           content:
            application/json:
             schema:
               type: object
             example:
               message: "successfully updated"
         '500':
            description: Internal Server Error

# ? Manage Hostel Routes
  /SA/getHostels:
    get:
      description: "to get available Hostels \n
                 in response we will get hostel info and \n their respective hostel authorities info\n auth required 
                      \n and also active:true/false attribute with each hostel"
      tags: 
        - SA
      responses:
        '200':
          description: fetched successfully
        '500':
          description: Internal Server Error

  /SA/addHostel:
    post:
      description: "
        Used to add hostel in hostel table. \n
        Do not send empty JSON on the backend"
      tags:
        - SA
      consumes:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
             newHostelNo: 1
             hostelName: "Spartans"
             type: "CS"
      responses:
        '200':
          description: Hostel added successfully
        '400':
          description: Hostel Allready exists
        '500':
          description: Internal Server Error

  /SA/removeHostel:
     delete:
       description: "
        this route is used to disable or permanently delete the hostel \n
        Send softdelte param true if want to disable \n
        Send softdelte param false if want to delete permanently"
       tags:
         - SA
       parameters:
         - name: hostelNo
           in: query
           description: hostelNo to Delete
           required: true
           schema:
           type: integer
         - name: softdelete
           in: query
           description: true means delete permanently, false means softdelete 
           required: true
           schema:
           type: boolean
       responses:
         '200':
           description: Hostel Removed successfully
           content:
            application/json:
             schema:
               type: object
             example:
               message: "successfully deleted"
         '400':
           description: Hostel Not Found
           content:
            application/json:
             schema:
               type: object
             example:
               message: "Hostel not found"
         '500':
            description: Internal Server Error

  /SA/enableHostel:
     post:
       description: "
        this route is used to enable a course if disabled \n
        Works on Course table \n
        auth required"
       tags:
         - SA
       consumes:
         - application/json
       requestBody:
         required: true
         content:
           application/json:
            schema:
              type: object
            example:
             bodyHostelNo: 1
       responses:
         '200':
           description: Hostel successfully enabled
           content:
            application/json:
             schema:
               type: object
             example:
               message: "successfully enabled"
         '400':
           description: Hostel Not Found or Already email enabled
           content:
            application/json:
             schema:
               type: object
             example:
               message: "Hostel Not Found or Already email enabled"
         '500':
            description: Internal Server Error
          
  /SA/updateHostel:
     patch:
       description: "
        this route is used to update  a Hostel \n
        Works on Hostel table \n
        auth required"
       tags:
         - SA
       consumes:
         - application/json
       requestBody:
         required: true
         content:
           application/json:
            schema:
              type: object
            example:
             bodyHostelNo: 1
             hostelName: "Spartans"
             type: "Boys"
       responses:
         '200':
           description: Hostel Updated successfully
           content:
            application/json:
             schema:
               type: object
             example:
               message: "successfully updated"
         '500':
            description: Internal Server Error

#?  Manage Admins Routes
  /SA/getAdmins:
    get:
      description: "1) Api to get available admins \n
                 2) in response we will get admin info \n
                3) **auth required** \n 
                4) and also **`active:true/false`** attribute with each admin to tell if login access is there or not"
      tags: 
        - SA
      responses:
        '200':
          description: fetched successfully
        '500':
          description: Internal Server Error in getAdmins Controller

  /SA/giveLoginAccess:
     post:
       description: "
        1) This route is used to give login access to HA \n
        2) Works on User table \n"
       tags:
         - SA
       consumes:
         - application/json
       requestBody:
         required: true
         content:
           application/json:
            schema:
              type: object
            example:
             emailOfHA: "example@example.com"
       responses:
         '200':
           description: successfully granted login access
           content:
            application/json:
             schema:
               type: object
             example:
               message: "successfully granted login access"
         '400':
           description: Email not found or allread granted access
           content:
            application/json:
             schema:
               type: object
             example:
               message: "Email not found or allread granted access"
         '500':
            description: Internal Server Error in GiveLoginAccess Controller

  /SA/revokeLoginAcess:
     post:
       description: "
        1) This route is used to revoke login access of HA\n
        2) Works on user table \n"
       tags:
         - SA
       consumes:
         - application/json
       requestBody:
         required: true
         content:
           application/json:
            schema:
              type: object
            example:
             emailOfHA: "example@example.com"
       responses:
         '200':
           description: Successfull revoked access
           content:
            application/json:
             schema:
               type: object
             example:
               message: "Successfull revoked access"
         '400':
           description: Email not found or allready revoked access
           content:
            application/json:
             schema:
               type: object
             example:
               message: "Email not found or allready revoked access"
         '500':
            description: Internal Server Error

  /SA/changeHostel:
     post:
       description: "
        1) This route is used to change hostel of HA \n
        2) Works on HA table \n"
       tags:
         - SA
       consumes:
         - application/json
       requestBody:
         required: true
         content:
           application/json:
            schema:
              type: object
            example:
             emailOfHA: "example@example.com"
             newHostelNo: 10
       responses:
         '400':
           description: Given Hostel Not Found
           content:
            application/json:
             schema:
               type: object
             example:
               message: "Given Hostel Not Found"
         '200':
           description: Hostel Changed to Given Hostel
           content:
            application/json:
             schema:
               type: object
             example:
               message: "Hostel Changed to Given Hostel"
         '500':
            description: Internal Server Error

  /SA/adminReg:
     post:
       description: "
        1) it register admin \n
        2) Works on HA and user table table \n"
       tags:
         - SA
       consumes:
         - application/json
       requestBody:
         required: true
         content:
           application/json:
            schema:
              type: object
            example:
             email: "example@example.com"
             name: "admin"
             roleType: "Office-Admin"
             mobile: "1234567890"
             password: "asdfghjkl"
             hostel: 11
       responses:
         '200':
           description: Hostel-Authority(Member) Register into db Successfully
           content:
            application/json:
             schema:
               type: object
             example:
               message: "Hostel-Authority(Member) Register into db Successfully"
         '500':
            description: Internal Server Error

  /SA/bulkCreate:
    post:
      description: used to upload rooms in bulk using csv file
      tags:
        - SA
      consumes:
      - multipart/form-data
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The CSV file to upload
      responses:
        '200':
          description: will return json array at 0 index entered data and at index 1 data with errors
        '400':
          description: Syntax Error
        '500':
          description: Internal Server Error